version: "3.3"
services:
  api:
    build: 
      context: ./infra/phpfpm
    volumes:
      - ./api:/var/www/html
    depends_on: 
      - mysql
    ports:
      - "9000:9000"
  nginx:
    build: 
      context: ./infra/nginx
    volumes:
      # https://github.com/vuejs/vue-cli/pull/6221
      - ./app:/var/www/html
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
  mysql:
    build: 
      context: ./infra/mysql
    ports:
      - "3306:3306"
  nodejs:
    build: 
      context: ./infra/nodejs
    volumes:
      - ./app:/var/www/html
    command: sh -c "cd /var/www/html && npm install && npm run serve"
    ports:
      - "8080:8080"